### ISSUE TITLE
FSE: CoBlocks site design conflict

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/go#856]
```php
Fatal error: Uncaught Error: Call to undefined function Go\Core\get_design_style() in /var/www/html/wp-content/plugins/coblocks/includes/class-coblocks-site-design.php:126 Stack trace: #0 /var/www/html/wp-content/plugins/coblocks/includes/class-coblocks-site-design.php(424): CoBlocks_Site_Design::get_coblocks_site_design_data() #1 /var/www/html/wp-includes/class-wp-hook.php(308): CoBlocks_Site_Design->editor_assets('') #2 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #3 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #4 /var/www/html/wp-admin/site-editor.php(156): do_action('enqueue_block_e...') #5 {main} thrown in /var/www/html/wp-content/plugins/coblocks/includes/class-coblocks-site-design.php on line 126
```

The call to the `get_design_style` function in CoBlocks seems to be crashing.

**Comment by jrtashjian** [comment]
Good callout. This is something we realized we would lose in the transition since FSE handles it all now. We could possibly conditionally load it in CoBlocks by detecting the active version of Go on a site. So less than v2 would load it, v2 or greater would not.

**Comment by jrtashjian** [comment]
Created a new issue in CoBlocks for tracking, and also Jira for internal tracking.

Closing this.
